version: '3.9'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REGISTRY_MIRROR=https://registry.docker-cn.com
    ports:
      - '3000:3000'
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin123
      - DATABASE_NAME=content_sharing_platform
