version: '3'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REGISTRY_MIRROR=https://registry.docker-cn.com
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin123
      - DATABASE_NAME=content_sharing_platform

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: content_sharing_platform
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data:
